bot:
  token:
  admins:
  super_admins: []
  REFERRAL_PERCENT: 10.0
  SUBSCRIPTION_1_MONTH: 60.0
  SUBSCRIPTION_6_MONTH: 3000.0
  SUBSCRIPTION_12_MONTH: 5000.0
  SUBSCRIPTION_PRO_1_MONTH: 70.0
  SUBSCRIPTION_PRO_6_MONTH: 9000.0
  SUBSCRIPTION_PRO_12_MONTH: 18000.0
  SUPPORT_CHAT_ID:
  SUPPORT_MESSAGES: {}
  WITHDRAW_BALANCE: 3000.0
  INSTRUCTION: '0'
  START_MESSAGE: '0'
  BONUS: 200.0
  BONUS_TEXT: Мы дарим на твой реферальный счет 250 ₽
  AUTO_DELETE_MESSAGE: '0'
  RESPONSE: '0'
db:
  user:
  password:
  database:
  host: db
  port:
  timezone: Europe/Moscow
  dialect: asyncpg
webhook: null
merchants:
- merchant:
  shop_id:
  api_key:
- merchant:
  shop_id:
  api_key:
