bot:
  token: 6188933942:AAEydKR__IrAjW19wNj68AATIq6qrUBgIjQ
  admins:
  - 398349792
  super_admins: []
  REFERRAL_PERCENT: 10.0
  SUBSCRIPTION_1_MONTH: 60.0
  SUBSCRIPTION_6_MONTH: 3000.0
  SUBSCRIPTION_12_MONTH: 5000.0
  SUBSCRIPTION_PRO_1_MONTH: 70.0
  SUBSCRIPTION_PRO_6_MONTH: 9000.0
  SUBSCRIPTION_PRO_12_MONTH: 18000.0
  SUPPORT_CHAT_ID: -4151697334
  SUPPORT_MESSAGES: {}
  WITHDRAW_BALANCE: 3000.0
  INSTRUCTION: '0'
  START_MESSAGE: '0'
  BONUS: 200.0
  BONUS_TEXT: Мы дарим на твой реферальный счет 250 ₽
  AUTO_DELETE_MESSAGE: '0'
  RESPONSE: '0'
db:
  user: postgres
  password: postgres
  database: chat_scanner
  host: db
  port: 5432
  timezone: Europe/Moscow
  dialect: asyncpg
webhook: null
merchants:
- merchant: yookassa
  shop_id: null
  api_key: 381764678:TEST:83823
- merchant: crypto_pay
  shop_id: null
  api_key: 177570:AAbAxDKU7ADpvR8LcXXCefhXAJHcZMxJWn7
