version: "3.9"
services:
  bot:
    build: ./
    restart: always
    command: python chat_scanner/main.py
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
    environment:
      - DB__HOST=db
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_scanner
    ports:
      - "5400:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
